---
- name: docker installing section
  hosts: kong
  gather_facts: true
  connection: ssh
  user: root
  vars_files:
    - vars.yml
  tasks:
    - include: tasks/docker.yml
- name: postgresql installing/configuring section
  hosts: kong
  gather_facts: true
  connection: ssh
  user: root
  vars_files:
    - vars.yml
  tasks:
    - include: tasks/postgresql.yml

- name: kong installing/configuring/starting section
  hosts: kong
  gather_facts: true
  connection: ssh
  user: root
  vars_files:
    - vars.yml
  vars:
    wrk_dir: "{{ kongpath }}"
    wrk_user: root
    wrk_group: root
  tasks:
    - include: tasks/kong.yml