- name: Installing required packages for postgresql
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: present
  loop:
    - postgresql-12
    - postgresql-contrib
    - postgresql-client-12
- name: allow docker network to access postgresql
  ansible.builtin.lineinfile:
    path: /etc/postgresql/12/main/pg_hba.conf
    line: "host    all    all    172.0.0.0/8    md5"
    state: present
- name: allow docker network to access postgresql
  ansible.builtin.lineinfile:
    path: /etc/postgresql/12/main/pg_hba.conf
    line: "host    all    all    192.168.0.0/16    md5"
    state: present

- name: allow docker network to access postgresql
  ansible.builtin.lineinfile:
    path: /etc/postgresql/12/main/postgresql.conf
    line: "listen_addresses = '*'"
    state: present
- copy:
    src: files/{{ item }}
    dest: "{{kongpath}}/{{ item }}"
    owner: root
    group: root
    mode: 0755
  loop:
    - connections.js
    - adapter.js
    
- template:
    src: templates/kongdbinit.j2
    dest: /var/lib/postgresql/kongdbinit.sql
    owner: postgres
    group: postgres
    mode: 0700
- template:
    src: templates/execsql.j2
    dest: /execsql.sh
    owner: root
    group: root
    mode: 0700
- ansible.builtin.command: "/execsql.sh"
  #become: true
  #become_user: postgres
- name: systemctl enable/restart postgresql
  systemd:
    daemon_reload: yes
    name: postgresql
    state: restarted
    enabled: yes
    masked: no
